// Code generated by gobind. DO NOT EDIT.

// Java class go.bindtest.misc.Misc is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=go.bindtest github.com/danbrough/gobindtest/core/misc
//go:build  linux || windows 
//+build linux, windows 
package go.bindtest.misc;

import go.Seq;

public abstract class Misc {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Misc() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	private static final class proxyPrinter implements Seq.Proxy, Printer {
		private final int refnum;
		
		@Override public final int incRefnum() {
		      Seq.incGoRef(refnum, this);
		      return refnum;
		}
		
		proxyPrinter(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
		
		public native void print(String msg);
	}
	
	
	public static native String getMessage();
	public static native void test2(byte[] data);
	public static native void testPrinter(Printer printer);
}
