// Code generated by gobind. DO NOT EDIT.

// Java class go.bindtest.misc.Printer is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=go.bindtest github.com/danbrough/gobindtest/misc
//go:build  linux || windows 
//+build linux, windows 
package go.bindtest.misc;

import go.Seq;

public interface Printer {
	public void print(String msg);
	
}

