// Code generated by gobind. DO NOT EDIT.

// Java class go.bindtest.hello.Hello is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java -javapkg=go.bindtest github.com/danbrough/gobindtest/core/hello
//go:build  linux || windows 
//+build linux, windows 
package go.bindtest.hello;

import go.Seq;

public abstract class Hello {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Hello() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	
	
	public static native String getMessage();
	// skipped function Test with unsupported parameter or return types
	
	public static native void test2(byte[] data);
}
